### ISSUE TITLE
How to upgrade version to match current one?

### ISSUE THREAD

**Issue by Warns** [mhewedy/vermin#39]
Hi Muhammad, thanks for this tool.

Is changing the `k8s_version=` to `1.20.0` enough to do the upgrade? Or do we need to upgrade other packages too, to match the k8s version such as Docker etc?

**Comment by mhewedy** [comment]
You are talking about this post: https://mohewedy.medium.com/install-kubernetes-cluster-in-virtual-machines-the-easy-way-337ef0c4e37f

The answer is it I am not sure, but it deserves trying.

One this to note however, I've updated the post to use `ubuntu/focal64` instead of `ubuntu/focal`.

**Comment by mhewedy** [comment]
Did this work for you?

**Comment by Warns** [comment]
Hi @mhewedy sorry for late response. Sorry for asking an unrelative question here that I wasn't aware of. Also, can't believe how you could relate that it was about your post on medium 🙂 

I tried it and it worked just fine. It just updated the k8s version as intended.

**Comment by mhewedy** [comment]
No problem. Glad it worked 😊
