### ISSUE TITLE
Cannot start VMs

### ISSUE THREAD

**Issue by toduythienluong** [mhewedy/vermin#40]
Hi, 

just tried to create a VM with this command 
`vermin create ubuntu/focal64`

it got stuck while starting the VM, even though I can see the VM is created, up and running on the Virtual Box, I can log into the VM as well, can you hint a clue as to why the issue happened?

![image](https://github.com/mhewedy/vermin/assets/92596157/b0791524-7ba7-4f2c-9160-cf4839194472)

**Comment by akhiljns** [comment]
hey I'm facing similar issue, did you get it working on windows yet?

**Comment by akhiljns** [comment]
@mhewedy on debugging this issue it seems that come network elements contains carriage return and that fails 

`for _, line := range lines {
		s := strings.SplitN(line, ":", 2)

		key := strings.TrimSpace(s[0])
		value := strings.TrimSpace(s[1])
		elements[key] = value
	}`

this split, i'm raising a PR to fix this
