### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by yasser-abbasi-git** [mhewedy/vermin#41]
I get this error when trying to create a vm. I have tried a couple of differente images and get the same error everytime. The VM is created though and in a running state but I'm not sure if the given shell script executed.  I triedn creating a vm from an image without any shell script and still got the same issue. So, I'm guessing the script never executed as vermin failed during the create step.

Any ideas?

![image](https://github.com/mhewedy/vermin/assets/133650588/f162b3d4-e18a-423f-8a98-623935edb6b2)

**Comment by akhiljns** [comment]
hey I'm facing similar issue, did you get it working on windows yet?

I'm getting similar error when i try to ssh into the vm

when I try vermin start vm, i get VM already running, use "vermin ssh vm_01" to ssh into the VM.
