### ISSUE TITLE
Permission denied while changing hostname

### ISSUE THREAD

**Issue by akhiljns** [mhewedy/vermin#49]
`exit status 1 bash: /etc/hostname: Permission denied`

getting this error after vm gets created and connection is estabilished but while executing this command

_fmt.Sprintf("sudo sh -c 'echo %s > /etc/hostname'", newHostname)_

@mhewedy does this error sound familiar to you? I'm stuck with this now, will look into this when I get some time

**Comment by akhiljns** [comment]
Hey @mhewedy i checked into this code and tried running the ssh manually creating the exact command from golang code

unfortunately it says access denied for doing ssh

![Screenshot 2024-04-03 220503](https://github.com/mhewedy/vermin/assets/22194681/b823ea2c-d6d4-42ea-b327-c7a95e0c4773)

how is the private key getting created?

**Comment by mhewedy** [comment]
Which image you are trying to create?

The point is, Vagrant images come with a preinstalled vagrant public key installed. and so we use the vagrant private key to ssh into the VM.

**Comment by akhiljns** [comment]
> Which image you are trying to create?
> 
> The point is, Vagrant images come with a preinstalled vagrant public key installed. and so we use the vagrant private key to ssh into the VM.

i'm using ubuntu/focal64, ahh ok but i think the private key we are using is not related to the vagrant public key, I'll spend sometime today to figure this out

can't we use username and password to login into vm via ssh? the default password

**Comment by mhewedy** [comment]
> > Which image you are trying to create?
> > The point is, Vagrant images come with a preinstalled vagrant public key installed. and so we use the vagrant private key to ssh into the VM.
> 
> i'm using ubuntu/focal64, ahh ok but i think the private key we are using is not related to the vagrant public key, I'll spend sometime today to figure this out
> 
> can't we use username and password to login into vm via ssh? the default password

this private key used to work with vagrant public key, unless they changed the private/public key pair.

we can, but the private/public key with no password is usually more convenient

**Comment by akhiljns** [comment]
> > > Which image you are trying to create?
> > > The point is, Vagrant images come with a preinstalled vagrant public key installed. and so we use the vagrant private key to ssh into the VM.
> > 
> > 
> > i'm using ubuntu/focal64, ahh ok but i think the private key we are using is not related to the vagrant public key, I'll spend sometime today to figure this out
> > can't we use username and password to login into vm via ssh? the default password
> 
> this private key used to work with vagrant public key, unless they changed the private/public key pair.
> 
> we can, but the private/public key with no password is usually more convenient

OK so on debugging this issue its not the problem of ssh, its logging into the container just fine but the main problem is 

cnd := fmt.Sprintf("sudo sh -c 'echo %s > /etc/hostname'", newHostname)

this is how you created the comnmand

ssh.Execute(vmName, cmd)

when It runs this

it gives me /etc/hostname: Permission denied

now i debugged it a little bit and found out that , when i tried running command myself

sudo sh -c "echo 01 > /etc/hostname"

this runs successfully inside the vm but 

sudo sh -c echo 01 > /etc/hostname

this gives me similar error permission denied

that means somehow its removing the ' ' single quotes used there, also I tried removing single quotes and using "" with escape character ubt i got same error 

fmt.Sprintf("sudo sh -c \"echo %s > /etc/hostname\"", newHostname)

**Comment by akhiljns** [comment]
@mhewedy turns out this was just a problem with how command strings were formed, thoese were not compatible in Powershell

raising a PR to fix it
