### ISSUE TITLE
Installation / Upgrades

### ISSUE THREAD

**Issue by paul-hammant** [mhewedy/vermin#8]
1. You have a link that goes to https://github.com/mhewedy/vermin#Automatic-installation but that doesn't exist.

2. How will upgrades work?  Does vermin inform you that and upgrade is available?

3) You have H1 sections Installation, Usage, More Installation options. Perhaps "More installation options" should be a H2 inside "Installation" instead of where it is

**Comment by mhewedy** [comment]
Thanks for reporting the issue.

1. The link is now fixed at `README.md`, you can reach it at https://github.com/mhewedy/vermin#install-vermin

2. Vermin do check for the newest released version every while (currently based on a random number see [updater.go](https://github.com/mhewedy/vermin/blob/1783bb05c18bfe997175c2726d96cc116f0c7a2d/config/updater.go)), so whenever it finds a new version available, it prints the message: 
**New version available &lt;latest version number&gt;, check https://github.com/mhewedy/vermin#install-vermin**
And to upgrade, you just execute the same install command.

3. Thanks for your valuable suggestion, `README.md` updated as well.

Again, I am very grateful for reporting this issue.

**Comment by mhewedy** [comment]
you can reopen in future if you have updates
